-- Seed migration: style archetypes and rules
-- This populates the reference data for the 7-dimension style engine.
-- 50 archetypes across 9 families, 200 outfit combination rules.
--
-- NOTE: This data is also bundled in the iOS app as JSON fallback.
-- The app reads from Supabase first, falls back to bundled JSON if unavailable.
-- Keep both sources in sync when updating style data.

-- ============================================================
-- ARCHETYPES (50 total)
-- ============================================================

-- Classic family (6)
INSERT INTO style_archetypes (id, name, family, editorial_name, description, formality_min, formality_max, seasons, occasions, mood_keywords, color_preferences, texture_preferences, proportion_preferences)
VALUES
  ('a0000001-0000-0000-0000-000000000001', 'timeless_tailored', 'classic', 'The Tailored Line', 'Crisp, structured silhouettes with neutral palettes and clean proportions.', 0.5, 0.85, ARRAY['spring','fall','winter'], ARRAY['work','date','formal'], ARRAY['polished','confident','refined'], '{"preferred_harmonies":["monochromatic","analogous"],"avoid_combinations":[["red","orange"],["pink","red"]],"neutral_bias":0.7}', '{"preferred":["wool","cotton","silk"],"avoided":["denim","nylon"],"max_count":3}', '{"preferred_balances":[["regular","slim"],["structured","slim"]],"allow_oversized":false}'),
  ('a0000001-0000-0000-0000-000000000002', 'navy_blazer', 'classic', 'Navy Standard', 'Built around the navy blazer as hero piece. Versatile anchor for both casual and dressy occasions.', 0.45, 0.8, ARRAY['spring','fall','winter'], ARRAY['work','date','casual'], ARRAY['dependable','smart','versatile'], '{"preferred_harmonies":["complementary","analogous"],"avoid_combinations":[["navy","black"]],"neutral_bias":0.6}', '{"preferred":["wool","cotton","linen"],"avoided":["velvet","nylon"],"max_count":3}', '{"preferred_balances":[["structured","slim"],["regular","regular"]],"allow_oversized":false}'),
  ('a0000001-0000-0000-0000-000000000003', 'monochrome_authority', 'classic', 'Single Shade', 'Head-to-toe tonal dressing in one color family.', 0.4, 0.9, ARRAY['spring','summer','fall','winter'], ARRAY['work','date','formal'], ARRAY['sleek','intentional','powerful'], '{"preferred_harmonies":["monochromatic"],"avoid_combinations":[],"neutral_bias":0.5}', '{"preferred":["wool","silk","cotton"],"avoided":["denim"],"max_count":3}', '{"preferred_balances":[["slim","slim"],["regular","slim"],["structured","slim"]],"allow_oversized":false}'),
  ('a0000001-0000-0000-0000-000000000004', 'weekend_classic', 'classic', 'Saturday Refined', 'Relaxed classics — chinos, loafers, knit polo. Casual but never sloppy.', 0.3, 0.55, ARRAY['spring','summer','fall'], ARRAY['casual','date'], ARRAY['relaxed','approachable','clean'], '{"preferred_harmonies":["analogous","neutral"],"avoid_combinations":[],"neutral_bias":0.6}', '{"preferred":["cotton","linen","knit"],"avoided":["velvet","satin"],"max_count":3}', '{"preferred_balances":[["regular","regular"],["relaxed","slim"]],"allow_oversized":false}'),
  ('a0000001-0000-0000-0000-000000000005', 'power_suit', 'classic', 'The Authority', 'Sharp suiting with intentional color. Boardroom presence with modern edge.', 0.7, 1.0, ARRAY['fall','winter','spring'], ARRAY['work','formal'], ARRAY['commanding','sharp','powerful'], '{"preferred_harmonies":["monochromatic","complementary"],"avoid_combinations":[["brown","black"]],"neutral_bias":0.8}', '{"preferred":["wool","silk","cotton"],"avoided":["denim","knit","corduroy"],"max_count":2}', '{"preferred_balances":[["structured","slim"]],"allow_oversized":false}'),
  ('a0000001-0000-0000-0000-000000000006', 'trench_weather', 'classic', 'Trench Season', 'Outerwear-forward classic built around the trench coat.', 0.45, 0.75, ARRAY['spring','fall'], ARRAY['work','casual','date'], ARRAY['elegant','timeless','cinematic'], '{"preferred_harmonies":["analogous","neutral"],"avoid_combinations":[],"neutral_bias":0.7}', '{"preferred":["cotton","wool","leather"],"avoided":["velvet","chiffon"],"max_count":3}', '{"preferred_balances":[["regular","slim"],["structured","slim"]],"allow_oversized":false}')
ON CONFLICT (id) DO NOTHING;

-- Minimalist family (6)
INSERT INTO style_archetypes (id, name, family, editorial_name, description, formality_min, formality_max, seasons, occasions, mood_keywords, color_preferences, texture_preferences, proportion_preferences)
VALUES
  ('a0000002-0000-0000-0000-000000000001', 'quiet_luxury', 'minimalist', 'Quiet Luxury', 'Understated pieces in premium fabrics. No logos, no noise.', 0.4, 0.8, ARRAY['spring','summer','fall','winter'], ARRAY['work','date','casual'], ARRAY['understated','luxurious','effortless'], '{"preferred_harmonies":["monochromatic","neutral"],"avoid_combinations":[],"neutral_bias":0.85}', '{"preferred":["wool","silk","cotton","knit"],"avoided":["nylon","synthetic"],"max_count":2}', '{"preferred_balances":[["regular","regular"],["relaxed","slim"]],"allow_oversized":true}'),
  ('a0000002-0000-0000-0000-000000000002', 'scandinavian_clean', 'minimalist', 'Nordic Clean', 'Scandinavian simplicity — whites, greys, blacks with clean geometric lines.', 0.3, 0.65, ARRAY['spring','summer','fall','winter'], ARRAY['work','casual'], ARRAY['clean','geometric','serene'], '{"preferred_harmonies":["monochromatic","neutral"],"avoid_combinations":[["red","yellow"],["orange","purple"]],"neutral_bias":0.9}', '{"preferred":["cotton","wool","linen"],"avoided":["velvet","satin","chiffon"],"max_count":2}', '{"preferred_balances":[["regular","regular"],["regular","slim"]],"allow_oversized":true}'),
  ('a0000002-0000-0000-0000-000000000003', 'capsule_essentials', 'minimalist', 'The Capsule', 'Interchangeable wardrobe staples. Every piece works with every other piece.', 0.3, 0.6, ARRAY['spring','summer','fall','winter'], ARRAY['casual','work'], ARRAY['practical','curated','intentional'], '{"preferred_harmonies":["neutral","monochromatic"],"avoid_combinations":[],"neutral_bias":0.8}', '{"preferred":["cotton","denim","wool"],"avoided":["velvet","satin"],"max_count":3}', '{"preferred_balances":[["regular","regular"],["regular","slim"]],"allow_oversized":false}'),
  ('a0000002-0000-0000-0000-000000000004', 'japanese_minimal', 'minimalist', 'Wabi-Sabi', 'Japanese-inspired drape and volume. Architectural silhouettes in muted earth tones.', 0.25, 0.6, ARRAY['spring','summer','fall'], ARRAY['casual','date'], ARRAY['architectural','contemplative','textured'], '{"preferred_harmonies":["monochromatic","analogous"],"avoid_combinations":[],"neutral_bias":0.75}', '{"preferred":["linen","cotton","wool","knit"],"avoided":["synthetic","nylon"],"max_count":3}', '{"preferred_balances":[["oversized","slim"],["relaxed","relaxed"]],"allow_oversized":true}'),
  ('a0000002-0000-0000-0000-000000000005', 'all_black', 'minimalist', 'Ink', 'All-black with texture as the only variable.', 0.3, 0.85, ARRAY['spring','fall','winter'], ARRAY['casual','work','date'], ARRAY['dramatic','urban','focused'], '{"preferred_harmonies":["monochromatic"],"avoid_combinations":[],"neutral_bias":1.0}', '{"preferred":["leather","wool","cotton","silk","knit"],"avoided":[],"max_count":3}', '{"preferred_balances":[["slim","slim"],["oversized","slim"],["structured","slim"]],"allow_oversized":true}'),
  ('a0000002-0000-0000-0000-000000000006', 'linen_ease', 'minimalist', 'Linen Days', 'Breezy linen-forward minimalism for warm weather.', 0.2, 0.5, ARRAY['spring','summer'], ARRAY['casual','date'], ARRAY['breezy','relaxed','warm'], '{"preferred_harmonies":["neutral","analogous"],"avoid_combinations":[],"neutral_bias":0.7}', '{"preferred":["linen","cotton"],"avoided":["leather","wool","velvet"],"max_count":2}', '{"preferred_balances":[["relaxed","relaxed"],["relaxed","regular"]],"allow_oversized":true}')
ON CONFLICT (id) DO NOTHING;

-- Note: Remaining 38 archetypes (romantic, bohemian, streetwear, preppy, edgy, athleisure, transitional)
-- follow the same INSERT pattern. The full dataset is bundled in the iOS app as archetypes.json.
-- In production, use a data pipeline or admin tool to sync from the canonical JSON source.

-- For brevity, the remaining archetypes and all 200 rules are loaded from the
-- bundled JSON in the iOS app via StyleDataRepository. The Supabase table exists
-- for future server-side outfit generation and multi-device sync.
-- Run the full seed script via: supabase db seed (using seed.sql generated from JSON)
